
# html lang
language: zh

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /links

# stylesheets loaded in the <head>
stylesheets:

stylesheets_preload:
- https://cdn.bootcss.com/highlight.js/9.6.0/styles/github.min.css # for highlight
- https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap # for font
- https://fonts.googleapis.com/css?family=Noto+Serif+SC:500,700&display=swap # for font
- https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.4.2/tocbot.css # for toc basic style

# scripts loaded in the end of the body
scripts_defer:
- https://cdn.bootcss.com/highlight.js/9.6.0/highlight.min.js # for highlight
- /js/paper.js # for basic script


social:
  Github: https://github.com/random-yang
  Codepen: https://codepen.io/randomyang
  Dribbble: https://dribbble.com/randomyang
  Twitter: https://twitter.com/JHWviuDZH8bcvuM
  Email: mailto:decoderyang@gmail.com
  Rss: /atom.xml
# and more, you can add other link by the same way

# Uncomment to disable sidebar
# toc: false
# link: false
# archives: false
categories: false
# tags: false

# theme color
main_color: default # forest | grass | sky | sun | sea

# google Analytics
google_analytics_id: UA-151544816-1

# commend module
comment:
  enable: true
  appId: 1JY5EfOoNSaiEGcXhwrCs7dk-gzGzoHsz
  appKey: jXutXUNavOPDp92k9gQuMsv9
  placeholder: Say something...
  notify: false
  verify: false
  avatar: mp
